export { ROLES, ROLE_HIERARCHY, ROLE_LABELS, getRoleLabel, hasMinRole, type Role } from './roles';
export {
  ROLE_MANAGER,
  canAssignRole,
  getAssignableRoles,
  canManageUser,
  canCreateUsers,
  canToggleUserStatus,
  isDriverRole,
  DASHBOARD_ACCESS,
  canAccessDashboardArea,
  canAccessClientsDashboard,
  canAccessDriverSelfService,
  canCreateCalendarScheduledInvoice,
} from './permissions';
export {
  REMOVED_MODULE_KEYS,
  HIDDEN_ACTIVATION_MODULE_KEYS,
  filterTvdeModules,
  filterActivatableModules,
  isRemovedModule,
  isHiddenActivationModule,
  type RemovedModuleKey,
  type HiddenActivationModuleKey,
} from './modules';

import type { Role } from './roles';

export interface JwtPayload {
  sub: string;
  email: string;
  role: Role;
  tenantId: string | null;
  workspaceId: string | null;
  siteId: string | null;
  sessionId: string;
  /** Presente quando MASTER está a personificar este utilizador */
  impersonatorId?: string;
}

export interface ApiResponse<T = unknown> {
  success: boolean;
  data?: T;
  error?: string;
  message?: string;
}

export const DEFAULT_LIMITS = {
  storage_gb: 5,
  max_users: 10,
  max_products: 100,
  max_workspaces: 1,
  max_vehicles: 3,
  api_calls_month: 1000,
};

export {
  formatExVatInput,
  formatIncVatDisplay,
  formatVatPriceInput,
  getTaxRateById,
  priceExVatToIncVat,
  priceIncVatToExVat,
  EX_VAT_DECIMALS,
  roundExVat,
  roundMoney,
  type VatTaxRate,
} from './vat-pricing';

export { WEB_ROUTES, API_PATHS, STORAGE_KEYS } from './routes';
export {
  SEARCH_TYPE_LABELS,
  getSearchResultHref,
  type SearchResult,
  type SearchResultType,
} from './search';
export { getWebConfig } from './config.client';
export { getMoloniRedirectUri, isMoloniLocalRedirect } from './moloni-redirect';
export { isMoloniDemoCompany } from './moloni-demo';
export {
  parseMoloniInvoiceErrorMessage,
  type MoloniDocumentSetHealth,
  type MoloniDocumentSetHealthSeverity,
} from './moloni-document-set';
export {
  BILLING_DOCUMENT_TYPES,
  BILLING_ENTITY_TYPES,
  getDocumentTypeLabel,
  getBillingDocumentEditPath,
  type BillingNavItem,
  type MoloniDocumentType,
  type MoloniEntityType,
} from './billing-catalog';
export {
  CALENDAR_TIMEZONE_OPTIONS,
  DEFAULT_CALENDAR_TIMEZONE,
  formatDateTimeLocal,
  formatTimezoneLabel,
  getBusinessDayRange,
  getTodayRangeInTimezone,
  getZonedParts,
  isStartInPast,
  minStartDateTimeLocal,
  parseDateTimeLocal,
} from './calendar-timezone';
export { latLngToTile, osmEmbedUrl, osmTileUrl } from './calendar-map';
export {
  CALENDAR_RECURRENCE_OPTIONS,
  CALENDAR_INVOICE_RECURRENCE_OPTIONS,
  buildCalendarOccurrenceId,
  buildRecurrenceRule,
  getRecurrenceLabel,
  parseCalendarOccurrenceId,
  parseRecurrencePreset,
  type CalendarRecurrencePreset,
} from './calendar-recurrence';
export {
  EMAIL_DEFAULT_CC_KEY,
  EMAIL_DEFAULT_BCC_KEY,
} from './email-settings';
export {
  TENANT_BRANDING_LOGO_MIME_TYPES,
  TENANT_BRANDING_MAX_LOGO_BYTES,
  TENANT_BRANDING_MAX_WALLPAPER_BYTES,
  TENANT_BRANDING_WALLPAPER_MIME_TYPES,
  DEFAULT_LOGIN_WALLPAPER_PATH,
  TENANT_COMPANY_LOGO_SETTING_KEY,
  TENANT_LOGIN_WALLPAPER_SETTING_KEY,
  TENANT_LOGIN_LOGO_SCALE_SETTING_KEY,
  TENANT_LOGIN_LOGO_SCALES,
  parseTenantLoginLogoScale,
  type TenantLoginLogoScale,
  type TenantBrandingLogoMimeType,
  type TenantCompanyLogoMeta,
  type TenantLoginWallpaperMeta,
} from './tenant-branding';
export {
  CALENDAR_EVENT_TYPES,
  CALENDAR_SCHEDULED_INVOICE_ENABLED_KEY,
  CALENDAR_SCHEDULED_INVOICE_CATEGORY_ID_KEY,
  INVOICE_LINE_SUMMARY_MAX_LENGTH,
  type CalendarEventType,
  type CalendarScheduledInvoiceDraft,
  type CalendarScheduledInvoiceLine,
  type CalendarScheduledInvoiceSummary,
} from './calendar-scheduled-invoice';
export {
  CATALOG_IMPORT_MAX_ROWS,
  CATALOG_IMPORT_TEMPLATE_HEADERS,
  CATALOG_IMPORT_IGNORE,
  CATALOG_IMPORT_FIELD_OPTIONS,
  applyCatalogImportMapping,
  buildCatalogImportCsvFromRows,
  buildCatalogImportTemplateCsv,
  getCatalogImportColumnCount,
  guessCatalogFieldMapping,
  padCatalogImportRows,
  parseCatalogImportCsv,
  parseImportBoolean,
  CATALOG_IMPORT_MAPPABLE_FIELDS,
  normalizeCatalogImportRow,
  parseImportMoney,
  parseImportNumber,
  parseImportPercent,
  parseRawCsvRows,
  resolveImportExVatPrice,
  validateCatalogImportMapping,
  type CatalogImportFieldOption,
  type CatalogImportResult,
  type CatalogImportRowError,
} from './csv-import';
export {
  ADMIN_MGMT_MODULE_KEY,
  ADMIN_MGMT_MODULE_NAME,
  ADMIN_MGMT_VENCIMENTO_ORIGENS,
  ADMIN_MGMT_VENCIMENTO_STATUSES,
  ADMIN_MGMT_SEGURO_TIPO_AUTOMOVEL,
  ADMIN_MGMT_MAX_APOlices,
  ADMIN_MGMT_MAX_FATURA_ANEXOS,
  ADMIN_MGMT_FATURA_TIPOS,
  ADMIN_MGMT_FATURA_PAGAMENTO_STATUSES,
  ADMIN_MGMT_FATURA_METODOS_PAGAMENTO,
  ADMIN_MGMT_FATURA_ANEXO_MIME_TYPES,
  getAdminMgmtFaturaTipoLabel,
  getAdminMgmtFaturaPagamentoLabel,
  getAdminMgmtFaturaMetodoPagamentoLabel,
  type AdminMgmtFaturaAnexo,
  DEFAULT_ADMIN_MGMT_SEGURADORAS,
  DEFAULT_ADMIN_MGMT_TIPOS_PRODUTO,
  ADMIN_MGMT_APOlice_MIME_TYPES,
  isAdminMgmtSeguroTipoAutomovel,
  type AdminMgmtApoliceFile,
  ADMIN_MGMT_SEGURO_OBJETO_TIPOS,
  ADMIN_MGMT_SEGURO_PERIODICIDADES,
  ADMIN_MGMT_SEGURO_PAGAMENTO_STATUSES,
  ADMIN_MGMT_CONTRATO_TIPOS,
  ADMIN_MGMT_CONTRATO_PERIODICIDADES,
  ADMIN_MGMT_CONTRATO_STATUSES,
  ADMIN_MGMT_FISCAL_STATUSES,
  ADMIN_MGMT_IVA_REGIMES,
  ADMIN_MGMT_IVA_STATUSES,
  ADMIN_MGMT_IRS_TIPOS,
  ADMIN_MGMT_PRESTACAO_STATUSES,
  getAdminMgmtPrestacaoStatusLabel,
  computeAdminMgmtPrestacaoSummary,
  DEFAULT_ADMIN_MGMT_ALERT_DAYS,
  getAdminMgmtVencimentoOrigemLabel,
  getAdminMgmtVencimentoStatusLabel,
  getAdminMgmtVencimentoHref,
  vencimentoUrgencyClass,
  formatAdminMgmtMoney,
  formatAdminMgmtAlertTitle,
  formatAdminMgmtAlertSubject,
  type AdminMgmtVencimentoOrigem,
  type AdminMgmtVencimentoStatus,
} from './admin-mgmt';
export {
  VIRTUALIZATION_MODULE_KEY,
  VIRTUALIZATION_MODULE_NAME,
  VIRTUALIZATION_POLL_INTERVAL_OPTIONS,
  VIRTUALIZATION_DASHBOARD_REFRESH_OPTIONS,
  ZEROTIER_NETWORK_MEMBER_LIMIT,
  formatVirtualizationBytes,
  formatVirtualizationRatio,
  formatVirtualizationPercent,
  buildPbsApiToken,
  buildPveApiToken,
  extractPbsApiTokenId,
  extractPveApiTokenId,
  normalizePbsApiTokenSecret,
  normalizePbsApiTokenValue,
  normalizePveApiTokenSecret,
  normalizePveApiTokenValue,
  formatPbsAuthorizationHeader,
  formatPveAuthorizationHeader,
  formatProxmoxAuthError,
  isLikelyPbsBaseUrl,
  isLikelyPveBaseUrl,
  getVirtualizationBackupStatusLabel,
  virtualizationBackupStatusClass,
  VIRTUALIZATION_ALERT_LEVELS,
  VIRTUALIZATION_ALERT_STATUSES,
  VIRTUALIZATION_ALERT_KINDS,
  VIRTUALIZATION_ALERT_LEVEL_RANK,
  VIRTUALIZATION_ALERT_COOLDOWN_MINUTES,
  getVirtualizationAlertLevelLabel,
  getVirtualizationAlertKindLabel,
  virtualizationAlertLevelClass,
  virtualizationAlertLevelDotClass,
  type VirtualizationBackupStatus,
  type VirtualizationAlertLevel,
  type VirtualizationAlertStatus,
  type VirtualizationAlertKind,
  type VirtualizationAlertIncidentPublic,
  type VirtualizationAlertSummary,
  type VirtualizationDashboardData,
  type VirtualizationDatastoreSummary,
  type VirtualizationLatestBackup,
  type VirtualizationPbsServerDetail,
  type VirtualizationPbsServerPublic,
  type VirtualizationPveNodeSummary,
  type VirtualizationPveDashboardSummary,
  type VirtualizationPveStorageSummary,
  type VirtualizationPveGuest,
  type VirtualizationPveGuestType,
  type VirtualizationPveGuestNetwork,
  type VirtualizationPveGuestNetworkAddress,
  type VirtualizationPveConsoleSession,
  type VirtualizationPveSshSession,
  type VirtualizationPveGuestPingResult,
  type VirtualizationZerotierAccountPublic,
  type VirtualizationZerotierNetworkPublic,
  type VirtualizationZerotierRemoteNetwork,
  type VirtualizationZerotierMemberPublic,
  type VirtualizationZerotierJoinTargetPublic,
  type VirtualizationZerotierLocalHostPublic,
  type VirtualizationZerotierJoinTargetKind,
  type VirtualizationZerotierSshAuthMode,
  type VirtualizationZerotierJoinStatus,
  extractHostFromServerUrl,
  parseSshEndpoint,
  type VirtualizationPveServerDetail,
  type VirtualizationPveServerPublic,
  type VirtualizationSettingsPublic,
} from './virtualization';
export {
  formatWhatsappPhone,
  normalizeWhatsappPhoneDigits,
  whatsappPhonesMatch,
} from './whatsapp-phone';
export {
  WHATSAPP_BUSINESS_API_VERSIONS,
  WHATSAPP_PROVIDERS,
  WHATSAPP_PROVIDER_LABELS,
  WHATSAPP_TEMPLATE_CATEGORIES,
  WHATSAPP_TEMPLATE_CATEGORY_LABELS,
  WHATSAPP_TEMPLATE_NAME_PATTERN,
  LEGACY_PORTAL_HOSTS,
  applyPortalUrlToTemplates,
  extractWhatsappBodyVariableIndexes,
  findTemplatePortalUrlMismatches,
  getUrlHostname,
  isDynamicUrlButton,
  isLegacyPortalUrl,
  portalLoginPath,
  rewritePortalUrl,
  WHATSAPP_BUSINESS_EVENT_KEYS,
  WHATSAPP_BUSINESS_EVENT_META,
  WHATSAPP_BUSINESS_LANGUAGE_OPTIONS,
  formatWhatsappBusinessPhone,
  maskWhatsappAccessToken,
  parseWhatsappTemplateParameters,
  renderWhatsappTemplatePreview,
  type WhatsappBusinessAccountStatus,
  type WhatsappBusinessConfigPublic,
  type WhatsappBusinessCreateTemplateInput,
  type WhatsappBusinessCreateTemplateResult,
  type WhatsappBusinessEventKey,
  type WhatsappProvider,
  type WhatsappBusinessNotificationEventConfig,
  type WhatsappBusinessStatusResponse,
  type WhatsappBusinessTemplateButton,
  type WhatsappBusinessTemplateSummary,
  type WhatsappTemplateCategory,
} from './whatsapp-business';
export {
  USERNAME_PATTERN,
  USER_STATUS_OPTIONS,
  buildUserPhone,
  getPasswordRequirementChecks,
  isPasswordStrong,
  isValidUserPhone,
  isValidUsername,
  normalizeUsername,
  roleRequiresPhone,
  splitUserPhone,
  type PasswordRequirementCheck,
} from './user-validation';
export {
  USER_DOCUMENT_TYPES,
  USER_DOCUMENT_TYPE_LABELS,
  USER_DOCUMENT_VISIBILITIES,
  USER_DOCUMENT_VISIBILITY_LABELS,
  USER_DOCUMENT_MIME_TYPES,
  USER_DOCUMENT_MAX_BYTES,
  canViewUserProfile,
  canEditUserProfile,
  isAllowedUserDocumentMime,
  type UserDocumentType,
  type UserDocumentVisibility,
  type UserProfileFields,
  type UserDocumentItem,
  type UserProfileDetail,
  type UserProfileDetailUser,
} from './user-profile';
export {
  VEHICLE_COMMISSION_TYPES,
  VEHICLE_COMMISSION_TYPE_LABELS,
  VEHICLE_LIMIT_PLANS,
  VEHICLE_LIMIT_WHATSAPP_NUMBER,
  normalizeUserVehicleMatricula,
  formatUserVehicleMatricula,
  parseOptionalDecimal,
  parseOptionalYear,
  parseDateOnlyInput,
  formatDateOnlyInput,
  resolveVehicleLimitPlanType,
  getVehicleLimitPlanLabel,
  buildVehicleLimitWhatsappMessage,
  buildVehicleLimitWhatsappUrl,
  type VehicleCommissionType,
  type VehicleLimitPlanType,
  type UserVehicleRecord,
  type TenantVehicleLimits,
} from './user-vehicle';
export {
  STORAGE_GB_BYTES,
  gbToStorageBytes,
  storageBytesToGb,
  formatStorageBytes,
  storageUsagePercent,
  storageLimitAlertLevel,
  type TenantStorageBreakdown,
  type TenantStorageSummary,
} from './storage';
export {
  overlapDays,
  isUserVehicleActive,
  pickBestUserVehicleForPeriod,
  vehicleLimitUsagePercent,
  vehicleLimitAlertLevel,
  toDateOnlyUtc,
  type UserVehiclePeriodRecord,
} from './user-vehicle-overlap';
export {
  defaultPaymentWeekRange,
  type PaymentMoneyLine,
  type PaymentCalculationReceitas,
  type PaymentCalculationDespesas,
  type PaymentCalculationIds,
  type PaymentCalculation,
  type PaymentDriverOption,
} from './payment-calculator';
export {
  CARWASH_LICENSE_COUNTRIES,
  formatLicensePlateDisplay,
  formatPortugueseLicensePlate,
  normalizeLicensePlate,
  stripLicenseInput,
  validatePortugueseLicensePlate,
  type CarwashLicenseCountry,
} from './carwash-license-plate';
export {
  PORTAL_KINDS,
  PORTAL_KIND_LABELS,
  PORTAL_CONNECTION_STATUSES,
  PORTAL_CONNECTION_STATUS_LABELS,
  MYPRIO_SYNC_SCOPES,
  MYPRIO_SYNC_SCOPE_LABELS,
  UBER_SYNC_MODES,
  defaultUberReportRange,
  lisbonDatetimeLocalToIso,
  isoToLisbonDatetimeLocal,
  guessUberOrganizationsFromReports,
  guessUberReportTypesFromReports,
  uberReportTypeLabel,
  uberReportTypeFromReportName,
  uberReportMatchesType,
  uberReportRowKey,
  uberReportDisplayType,
  uberReportTypeOptionMatches,
  resolveUberReportType,
  UBER_REPORT_TYPE_CATALOG,
  DEFAULT_UBER_REPORT_TYPE,
  ymdToUberCompact,
  extractUberReportDatesFromName,
  uberReportMatchesPeriod,
  listUberPaymentReports,
  pickLatestUberReportForPeriod,
  type PortalKind,
  type PortalConnectionStatus,
  type PortalConnectionPublic,
  type PortalConnectInput,
  type PortalOtpInput,
  type PortalSyncResultSummary,
  type MyPrioSyncScope,
  type UberSyncMode,
  type UberSyncOptions,
  type UberReportTypeKey,
  type UberReportListItem,
} from './portal-rpa';
export type { PlatformHostStats } from './platform-host';
export {
  PT_MONTH_LABELS,
  currentMonthKey,
  parseMonthKey,
  getMonthUtcRange,
  currentYearMonthOptions,
} from './month-filter';
export {
  getYearWeekStart,
  getWeeksInYear,
  getWeekRange,
  getWeekNumber,
  shiftWeek,
  getLisbonCalendarDate,
  getCurrentWeek,
  parseWeekQuery,
  formatWeekDate,
} from './week-number';
export {
  SPREADSHEET_IMPORT_EXTENSIONS,
  cellToImportString,
  normalizeSpreadsheetRows,
  parseCsvTextToRows,
  parseSpreadsheetDateValue,
  dateFromLisbonWallClock,
  reinterpretUtcWallClockAsLisbon,
  findSpreadsheetHeaderRowIndex,
  isSpreadsheetImportFilename,
} from './spreadsheet-rows';
export {
  VIA_VERDE_PAGE_SIZE,
  parseViaVerdeRows,
  parseViaVerdeCsv,
  parseViaVerdeImportFileName,
  type ViaVerdeMovementItem,
  type ViaVerdeDashboardStats,
  type ViaVerdeImportRowError,
  type ViaVerdeParsedMovement,
  type ViaVerdeImportResult,
} from './via-verde';
export {
  ELECTRICITY_PAGE_SIZE,
  ELECTRICITY_IMPORT_FIELDS,
  guessElectricityFieldMapping,
  parseElectricityRows,
  parseElectricityCsv,
  parseElectricityImportFileName,
  type ElectricityImportField,
  type ElectricityChargeItem,
  type ElectricityDashboardStats,
  type ElectricityImportRowError,
  type ElectricityParsedCharge,
  type ElectricityImportResult,
} from './electricity';
export {
  COMBUSTIVEL_PAGE_SIZE,
  parseCombustivelRows,
  parseCombustivelCsv,
  parseCombustivelImportFileName,
  type CombustivelImportRowError,
  type CombustivelParsedTransaction,
  type CombustivelImportResult,
} from './combustivel';
export {
  UBER_CSV_REQUIRED_COLUMNS,
  UBER_DRIVER_NET_EARNINGS_DESCRIPTION,
  detectUberCsvKind,
  parseUberReportPeriodFromFilename,
  isUberDriverNetEarningsRow,
  parseUberCsv,
  parseUberImportFileName,
  type UberImportRowError,
  type UberParsedPayment,
  type UberImportResult,
  type UberCsvKind,
  type ParseUberCsvOptions,
} from './uber-import';
export {
  RECIBOS_VERDES_CSV_MAX_ROWS,
  parseRecibosVerdesCsv,
  mapSireTipoDocumento,
  type RecibosVerdesCsvParsedRow,
  type RecibosVerdesCsvParseResult,
  type RecibosVerdesImportPreviewRow,
  type RecibosVerdesImportResult,
  type RecibosVerdesCsvRowError,
} from './recibos-verdes-import';
