/** Frontend App Router paths — single source of truth for navigation/redirects. */
export const WEB_ROUTES = {
  home: '/',
  login: '/login',
  forgotPassword: '/forgot-password',
  resetPassword: '/reset-password',
  changePassword: '/dashboard/change-password',
  dashboard: {
    root: '/dashboard',
    tenants: '/dashboard/tenants',
    workspaces: '/dashboard/workspaces',
    clients: '/dashboard/clients',
    products: '/dashboard/products',
    users: '/dashboard/users',
    me: '/dashboard/me',
    audit: '/dashboard/audit',
    calendar: '/dashboard/calendar',
    woocommerce: {
      root: '/dashboard/woocommerce',
      stock: '/dashboard/woocommerce/stock',
      product: (id: number | string) => `/dashboard/woocommerce/products/${id}`,
    },
    shopify: {
      root: '/dashboard/shopify',
      customers: '/dashboard/shopify/customers',
      orders: '/dashboard/shopify/orders',
      product: (id: number | string) => `/dashboard/shopify/products/${id}`,
      order: (id: number | string) => `/dashboard/shopify/orders/${id}`,
    },
    stripe: {
      root: '/dashboard/stripe',
    },
    ecommerce: {
      root: '/dashboard/ecommerce',
      produtos: '/dashboard/ecommerce/produtos',
      marcas: '/dashboard/ecommerce/marcas',
      modelos: '/dashboard/ecommerce/modelos',
      navegacao: '/dashboard/ecommerce/navegacao',
      geral: '/dashboard/ecommerce/geral',
      wireframe: '/dashboard/ecommerce/wireframe',
      paginasEspeciais: '/dashboard/ecommerce/paginas-especiais',
      configuracoes: '/dashboard/ecommerce/configuracoes',
      categories: '/dashboard/ecommerce/categories',
      export: '/dashboard/ecommerce/export',
      orders: '/dashboard/ecommerce/orders',
      clientes: '/dashboard/ecommerce/clientes',
    },
    bookings: {
      root: '/dashboard/bookings',
      catalog: '/dashboard/bookings/catalog',
      settings: '/dashboard/settings/bookings',
    },
    publicBookings: {
      cancel: '/bookings/cancel',
    },
    carwash: {
      root: '/dashboard/carwash',
      clientes: '/dashboard/carwash/clientes',
      clienteDetail: (id: string) => `/dashboard/carwash/clientes/${id}`,
      fornecedores: '/dashboard/carwash/fornecedores',
      produtos: '/dashboard/carwash/produtos',
      servicos: '/dashboard/carwash/servicos',
      veiculos: '/dashboard/carwash/veiculos',
      folhaObra: '/dashboard/carwash/folha-obra',
      folhaObraDetail: (id: string) => `/dashboard/carwash/folha-obra/${id}`,
      folhaCaixa: '/dashboard/carwash/folha-caixa',
      relatorios: '/dashboard/carwash/relatorios',
      pickup: '/carwash/pickup',
    },
    adminMgmt: {
      root: '/dashboard/admin-mgmt',
      seguros: '/dashboard/admin-mgmt/seguros',
      contratos: '/dashboard/admin-mgmt/contratos',
      despesasPessoal: '/dashboard/admin-mgmt/despesas-pessoal',
      segurancaSocial: '/dashboard/admin-mgmt/seguranca-social',
      faturas: '/dashboard/admin-mgmt/faturas',
      clientes: '/dashboard/admin-mgmt/clientes',
      irs: '/dashboard/admin-mgmt/irs',
      iva: '/dashboard/admin-mgmt/iva',
      recibosVerdes: '/dashboard/admin-mgmt/recibos-verdes',
      vencimentos: '/dashboard/admin-mgmt/vencimentos',
      prestacoes: '/dashboard/admin-mgmt/prestacoes',
      configuracoes: '/dashboard/admin-mgmt/configuracoes',
    },
    virtualization: {
      root: '/dashboard/virtualization',
      pve: '/dashboard/virtualization/pve',
      pbs: '/dashboard/virtualization/pbs',
      alertas: '/dashboard/virtualization/alertas',
      configuracao: '/dashboard/virtualization/configuracao',
    },
    billing: {
      root: '/dashboard/billing',
      entidades: '/dashboard/billing/entidades',
      documentos: '/dashboard/billing/documentos',
      faturas: '/dashboard/billing/faturas',
      faturasSimplificadas: '/dashboard/billing/faturas-simplificadas',
      faturasRecibo: '/dashboard/billing/faturas-recibo',
      notasDebito: '/dashboard/billing/notas-debito',
      produtosCategorias: '/dashboard/billing/produtos/categorias',
      produtosCategoriaArtigos: (categoryId: number | string) =>
        `/dashboard/billing/produtos/categorias/${categoryId}/artigos`,
      produtosCategoriaArtigoNovo: (categoryId: number | string) =>
        `/dashboard/billing/produtos/categorias/${categoryId}/artigos/novo`,
      produtosCategoriaArtigoEditar: (categoryId: number | string, productId: number | string) =>
        `/dashboard/billing/produtos/categorias/${categoryId}/artigos/${productId}`,
    },
    whmcs: {
      root: '/dashboard/whmcs',
      clientes: '/dashboard/whmcs/clientes',
      cliente: (id: number | string) => `/dashboard/whmcs/clientes/${id}`,
      faturasWhmcs: '/dashboard/whmcs/faturas-whmcs',
      faturaWhmcs: (id: number | string) => `/dashboard/whmcs/faturas-whmcs/${id}`,
      servicos: '/dashboard/whmcs/servicos',
      dominios: '/dashboard/whmcs/dominios',
      produtos: '/dashboard/whmcs/produtos',
      /** Mapa local WHMCS → Moloni */
      faturas: '/dashboard/whmcs/faturas',
      settings: '/dashboard/settings/whmcs',
    },
    bolt: {
      root: '/dashboard/bolt',
      orders: '/dashboard/bolt/orders',
      orderDetail: (id: string) => `/dashboard/bolt/orders/${id}`,
      drivers: '/dashboard/bolt/drivers',
      vehicles: '/dashboard/bolt/vehicles',
      settings: '/dashboard/settings/bolt',
    },
    uber: {
      root: '/dashboard/uber',
    },
    viaVerde: {
      root: '/dashboard/via-verde',
    },
    eletricidade: {
      root: '/dashboard/eletricidade',
    },
    combustivel: {
      root: '/dashboard/combustivel',
    },
    pagamentos: {
      root: '/dashboard/pagamentos',
    },
    contaCorrente: {
      root: '/dashboard/conta-corrente',
    },
    meusPagamentos: {
      root: '/dashboard/meus-pagamentos',
    },
    documentos: {
      root: '/dashboard/documentos',
    },
    settings: {
      root: '/dashboard/settings',
      geral: '/dashboard/settings/geral',
      workspaces: '/dashboard/settings/workspaces',
      modules: '/dashboard/settings/modules',
      twoFa: '/dashboard/settings/two-fa',
      sms: '/dashboard/settings/sms',
      whatsapp: '/dashboard/settings/whatsapp',
      whatsappOfficial: '/dashboard/settings/whatsapp/oficial',
      whatsappGeneric: '/dashboard/settings/whatsapp/generica',
      moloni: '/dashboard/settings/moloni',
      whmcs: '/dashboard/settings/whmcs',
      bolt: '/dashboard/settings/bolt',
      woocommerce: '/dashboard/settings/woocommerce',
      shopify: '/dashboard/settings/shopify',
      stripe: '/dashboard/settings/stripe',
      pagamentos: '/dashboard/settings/pagamentos',
      entregas: '/dashboard/settings/entregas',
      ecommerce: '/dashboard/settings/ecommerce',
      bookings: '/dashboard/settings/bookings',
      calendar: '/dashboard/settings/calendar',
      smtp: '/dashboard/settings/smtp',
      audit: '/dashboard/settings/audit',
      security: '/dashboard/settings/security',
      tvde: {
        root: '/dashboard/settings/tvde',
        sessions: '/dashboard/settings/tvde/sessions',
        storage: '/dashboard/settings/tvde/storage',
        limiteViaturas: '/dashboard/settings/tvde/limite-viaturas',
        contratos: '/dashboard/settings/tvde/contratos',
        metodosPagamento: '/dashboard/settings/tvde/metodos-pagamento',
        contaCorrente: '/dashboard/settings/tvde/conta-corrente',
      },
    },
  },
} as const;

/** API path segments (without host or version prefix). */
export const API_PATHS = {
  health: '/health',
  auth: {
    login: '/auth/login',
    logout: '/auth/logout',
    refresh: '/auth/refresh',
    me: '/auth/me',
    sessions: '/auth/sessions',
    sessionById: (id: string) => `/auth/sessions/${id}`,
    impersonate: '/auth/impersonate',
    impersonateStop: '/auth/impersonate/stop',
    forgotPassword: '/auth/forgot-password',
    resetPassword: '/auth/reset-password',
    changePassword: '/auth/change-password',
    verifyPassword: '/auth/verify-password',
    twoFa: {
      status: '/auth/2fa/status',
      setup: '/auth/2fa/setup',
      verifySetup: '/auth/2fa/verify-setup',
      verify: '/auth/2fa/verify',
      disable: '/auth/2fa/disable',
      sendCode: '/auth/2fa/send-code',
      sendCodeMe: '/auth/2fa/send-code/me',
    },
  },
  tenants: {
    list: '/tenants',
    current: '/tenants/current',
    currentVehicleLimits: '/tenants/current/vehicle-limits',
    vehicleLimits: '/tenants/vehicle-limits',
    storage: '/tenants/storage',
    currentStorage: '/tenants/current/storage',
    currentSessions: '/tenants/current/sessions',
    currentSessionById: (sessionId: string) => `/tenants/current/sessions/${sessionId}`,
    sessions: '/tenants/sessions',
    sessionById: (sessionId: string) => `/tenants/sessions/${sessionId}`,
    sessionsRevokeAll: '/tenants/sessions/revoke-all',
    limits: (tenantId: string) => `/tenants/${tenantId}/limits`,
    byId: (tenantId: string) => `/tenants/${tenantId}`,
    deleteConfirmation: (tenantId: string) => `/tenants/${tenantId}/delete-confirmation`,
    resendAdminCredentials: (tenantId: string) => `/tenants/${tenantId}/resend-admin-credentials`,
    module: (tenantId: string, moduleKey: string) =>
      `/tenants/${tenantId}/modules/${moduleKey}`,
  },
  workspaces: {
    list: '/workspaces',
    quota: '/workspaces/quota',
    module: (workspaceId: string, moduleKey: string) =>
      `/workspaces/${workspaceId}/modules/${moduleKey}`,
  },
  workspaceRequests: {
    list: '/workspace-requests',
    approve: (id: string) => `/workspace-requests/${id}/approve`,
    reject: (id: string) => `/workspace-requests/${id}/reject`,
  },
  modules: { list: '/modules', health: '/modules/health' },
  clients: {
    list: '/clients',
    hierarchy: '/clients/hierarchy',
    byId: (id: string) => `/clients/${id}`,
  },
  products: { list: '/products', byId: (id: string) => `/products/${id}` },
  invoices: {
    list: '/invoices',
    byId: (id: string) => `/invoices/${id}`,
    issue: (id: string) => `/invoices/${id}/issue`,
    pdf: (id: string) => `/invoices/${id}/pdf`,
    sendEmail: (id: string) => `/invoices/${id}/send-email`,
    duplicate: (id: string) => `/invoices/${id}/duplicate`,
    markPaid: (id: string) => `/invoices/${id}/mark-paid`,
    markPending: (id: string) => `/invoices/${id}/mark-pending`,
    bulkMarkPaid: '/invoices/bulk/mark-paid',
  },
  calendar: {
    calendars: '/calendar/calendars',
    calendarById: (id: string) => `/calendar/calendars/${id}`,
    calendarMembers: (id: string) => `/calendar/calendars/${id}/members`,
    events: '/calendar/events',
    eventsToday: '/calendar/events/today',
    eventById: (id: string) => `/calendar/events/${id}`,
    eventAttachments: (eventId: string) => `/calendar/events/${eventId}/attachments`,
    eventAttachmentUpload: (eventId: string) => `/calendar/events/${eventId}/attachments/upload`,
    eventAttachmentDownload: (eventId: string, attachmentId: string) =>
      `/calendar/events/${eventId}/attachments/${attachmentId}/download`,
    eventAttachmentById: (eventId: string, attachmentId: string) =>
      `/calendar/events/${eventId}/attachments/${attachmentId}`,
    whatsappSettings: '/calendar/settings/whatsapp',
    remindersUpcoming: '/calendar/reminders/upcoming',
    reminderAck: (id: string) => `/calendar/reminders/${id}/ack`,
    reminderDismiss: (id: string) => `/calendar/reminders/${id}/dismiss`,
    shareableUsers: '/calendar/users',
    emailTemplate: '/calendar/settings/email-template',
    scheduledInvoiceSettings: '/calendar/settings/scheduled-invoice',
    processScheduledInvoicesCron: '/calendar/cron/process-scheduled-invoices',
    scheduledInvoiceResendEmail: (id: string) =>
      `/calendar/scheduled-invoices/${id}/resend-email`,
    geocode: '/calendar/geocode',
    mapPreview: '/calendar/map-preview',
  },
  woocommerce: {
    status: '/woocommerce/status',
    config: '/woocommerce/config',
    test: '/woocommerce/test',
    products: '/woocommerce/products',
    productById: (id: number | string) => `/woocommerce/products/${id}`,
    productVariations: (productId: number | string) => `/woocommerce/products/${productId}/variations`,
    productVariationById: (productId: number | string, variationId: number | string) =>
      `/woocommerce/products/${productId}/variations/${variationId}`,
    batchStock: '/woocommerce/stock/batch',
    stockRows: '/woocommerce/stock/rows',
    categories: '/woocommerce/categories',
    attributes: '/woocommerce/attributes',
  },
  shopify: {
    status: '/shopify/status',
    config: '/shopify/config',
    test: '/shopify/test',
    products: '/shopify/products',
    productById: (id: number | string) => `/shopify/products/${id}`,
    customers: '/shopify/customers',
    customerById: (id: number | string) => `/shopify/customers/${id}`,
    orders: '/shopify/orders',
    orderById: (id: number | string) => `/shopify/orders/${id}`,
    orderTransactions: (orderId: number | string) => `/shopify/orders/${orderId}/transactions`,
  },
  stripe: {
    status: '/stripe/status',
    config: '/stripe/config',
    test: '/stripe/test',
    paymentLinks: '/stripe/payment-links',
    paymentLinkById: (id: string) => `/stripe/payment-links/${id}`,
    paymentLinkDetails: (id: string) => `/stripe/payment-links/${id}/details`,
    paymentLinkSend: (id: string) => `/stripe/payment-links/${id}/send`,
    paymentLinkCancel: (id: string) => `/stripe/payment-links/${id}/cancel`,
    paymentLinkSync: (id: string) => `/stripe/payment-links/${id}/sync`,
    paymentLinkRefund: (id: string) => `/stripe/payment-links/${id}/refund`,
    paymentLinkDelete: (id: string) => `/stripe/payment-links/${id}`,
    webhook: '/stripe/webhook',
  },
  correosExpress: {
    status: '/correos-express/status',
    config: '/correos-express/config',
    test: '/correos-express/test',
    createOrderShipment: (orderId: string) => `/correos-express/orders/${orderId}/shipment`,
    createOrderPickup: (orderId: string) => `/correos-express/orders/${orderId}/pickup`,
    orderTracking: (orderId: string) => `/correos-express/orders/${orderId}/tracking`,
  },
  ecommerce: {
    status: '/ecommerce/status',
    config: '/ecommerce/config',
    shipping: '/ecommerce/shipping-config',
    shippingQuote: '/ecommerce/shipping-quote',
    paymentMethods: '/ecommerce/payment-methods',
    regenerateEmbedKey: '/ecommerce/config/regenerate-key',
    wireframeConfig: '/ecommerce/wireframe-config',
    specialPages: '/ecommerce/special-pages',
    media: '/ecommerce/media',
    mediaUpload: '/ecommerce/media/upload',
    mediaDownload: (id: string) => `/ecommerce/media/${id}/download`,
    mediaById: (id: string) => `/ecommerce/media/${id}`,
    publicMedia: (publicSlug: string, assetId: string) =>
      `/ecommerce/public/${publicSlug}/media/${assetId}`,
    products: '/ecommerce/products',
    productsBulk: '/ecommerce/products/bulk',
    productsImport: '/ecommerce/products/import',
    importWooCommerce: '/ecommerce/import/woocommerce',
    productById: (id: string) => `/ecommerce/products/${id}`,
    productImages: (productId: string) => `/ecommerce/products/${productId}/images`,
    productImageUpload: (productId: string) => `/ecommerce/products/${productId}/images/upload`,
    productImageDownload: (productId: string, imageId: string) =>
      `/ecommerce/products/${productId}/images/${imageId}/download`,
    productImageById: (productId: string, imageId: string) =>
      `/ecommerce/products/${productId}/images/${imageId}`,
    productImagesReorder: (productId: string) => `/ecommerce/products/${productId}/images/reorder`,
    productImagePrimary: (productId: string, imageId: string) =>
      `/ecommerce/products/${productId}/images/${imageId}/primary`,
    publicProductImage: (publicSlug: string, imageId: string) =>
      `/ecommerce/public/${publicSlug}/product-images/${imageId}`,
    categories: '/ecommerce/categories',
    categoryById: (id: string) => `/ecommerce/categories/${id}`,
    brands: '/ecommerce/brands',
    brandById: (id: string) => `/ecommerce/brands/${id}`,
    models: '/ecommerce/models',
    modelById: (id: string) => `/ecommerce/models/${id}`,
    navItems: '/ecommerce/nav-items',
    navItemById: (id: string) => `/ecommerce/nav-items/${id}`,
    exportPreview: '/ecommerce/export/preview',
    dashboardStats: '/ecommerce/dashboard/stats',
    orders: '/ecommerce/orders',
    customers: '/ecommerce/customers',
    customerById: (id: string) => `/ecommerce/customers/${id}`,
    orderById: (id: string) => `/ecommerce/orders/${id}`,
    publicCatalog: (publicSlug: string) => `/ecommerce/public/${publicSlug}/catalog`,
    publicCheckout: (publicSlug: string) => `/ecommerce/public/${publicSlug}/checkout`,
    publicOrder: (publicSlug: string, reference: string) =>
      `/ecommerce/public/${publicSlug}/orders/${reference}`,
    publicSpecialPages: (publicSlug: string) => `/ecommerce/public/${publicSlug}/special-pages`,
    publicSpecialPage: (publicSlug: string, pageKey: string) =>
      `/ecommerce/public/${publicSlug}/special-pages/${pageKey}`,
    publicContact: (publicSlug: string) => `/ecommerce/public/${publicSlug}/contact`,
  },
  bookings: {
    profiles: '/bookings/profiles',
    status: '/bookings/status',
    settings: '/bookings/settings',
    whatsappSettings: '/bookings/settings/whatsapp',
    regenerateEmbedKey: '/bookings/settings/regenerate-key',
    catalog: '/bookings/catalog',
    catalogById: (id: string) => `/bookings/catalog/${id}`,
    availability: '/bookings/availability',
    list: '/bookings',
    cancel: (id: string) => `/bookings/${id}/cancel`,
    publicServices: (publicSlug: string) => `/bookings/public/${publicSlug}/services`,
    publicAvailability: (publicSlug: string) => `/bookings/public/${publicSlug}/availability`,
    publicBook: (publicSlug: string) => `/bookings/public/${publicSlug}/book`,
    publicCalendarDays: (publicSlug: string) => `/bookings/public/${publicSlug}/calendar-days`,
    publicCancel: '/bookings/public/cancel',
  },
  carwash: {
    status: '/carwash/status',
    entities: '/carwash/entities',
    entityById: (id: string) => `/carwash/entities/${id}`,
    entityOverview: (id: string) => `/carwash/entities/${id}/overview`,
    catalogFormOptions: '/carwash/catalog/form-options',
    catalog: '/carwash/catalog',
    catalogImport: '/carwash/catalog/import',
    catalogById: (id: string) => `/carwash/catalog/${id}`,
    catalogPicker: '/carwash/catalog/picker',
    vehicles: '/carwash/vehicles',
    vehicleById: (id: string) => `/carwash/vehicles/${id}`,
    vehicleImageUpload: (vehicleId: string) => `/carwash/vehicles/${vehicleId}/images/upload`,
    vehicleImageDownload: (vehicleId: string, imageId: string) =>
      `/carwash/vehicles/${vehicleId}/images/${imageId}/download`,
    vehicleImageById: (vehicleId: string, imageId: string) =>
      `/carwash/vehicles/${vehicleId}/images/${imageId}`,
    workSheets: '/carwash/work-sheets',
    workSheetById: (id: string) => `/carwash/work-sheets/${id}`,
    workSheetActionCode: (id: string) => `/carwash/work-sheets/${id}/action-code`,
    workSheetRequestAuthorization: (id: string) => `/carwash/work-sheets/${id}/request-authorization`,
    workSheetReopen: (id: string) => `/carwash/work-sheets/${id}/reopen`,
    workSheetPaymentStatus: (id: string) => `/carwash/work-sheets/${id}/payment-status`,
    workSheetPickupSendLink: (id: string) => `/carwash/work-sheets/${id}/pickup/send-link`,
    workSheetPickupSignInApp: (id: string) => `/carwash/work-sheets/${id}/pickup/sign-in-app`,
    workSheetPickupSignature: (id: string) => `/carwash/work-sheets/${id}/pickup/signature`,
    workSheetSendCompletionEmail: (id: string) => `/carwash/work-sheets/${id}/send-completion-email`,
    overview: '/carwash/overview',
    billableLines: '/carwash/billable-lines',
    invoicesFromLines: '/carwash/invoices/from-lines',
    cashSheetDay: '/carwash/cash-sheets/day',
    cashSheetClose: '/carwash/cash-sheets/close',
    cashSheetById: (id: string) => `/carwash/cash-sheets/${id}`,
    cashSheetActionCode: (id: string) => `/carwash/cash-sheets/${id}/action-code`,
  },
  carwashPublic: {
    pickupInfo: '/carwash/public/pickup',
    pickupSign: '/carwash/public/pickup/sign',
  },
  adminMgmt: {
    status: '/admin-mgmt/status',
    dashboard: '/admin-mgmt/dashboard',
    vencimentos: '/admin-mgmt/vencimentos',
    vencimentoResolve: (id: string) => `/admin-mgmt/vencimentos/${id}/resolve`,
    vencimentoReopen: (id: string) => `/admin-mgmt/vencimentos/${id}/reopen`,
    settings: '/admin-mgmt/settings',
    notificationsStatus: '/admin-mgmt/notifications/status',
    notificationsTest: '/admin-mgmt/notifications/test',
    seguros: '/admin-mgmt/seguros',
    seguroById: (id: string) => `/admin-mgmt/seguros/${id}`,
    seguroApoliceUpload: (id: string) => `/admin-mgmt/seguros/${id}/apolices`,
    seguroApoliceById: (seguroId: string, apoliceId: string) =>
      `/admin-mgmt/seguros/${seguroId}/apolices/${apoliceId}`,
    clientes: '/admin-mgmt/clientes',
    clienteLookup: '/admin-mgmt/clientes/lookup',
    clienteImport: '/admin-mgmt/clientes/import',
    clienteById: (id: string) => `/admin-mgmt/clientes/${id}`,
    clienteLancamentos: (id: string) => `/admin-mgmt/clientes/${id}/lancamentos`,
    clienteLancamentoPreview: (id: string) => `/admin-mgmt/clientes/${id}/lancamentos/preview`,
    clienteLancamentoById: (clienteId: string, lancamentoId: string) =>
      `/admin-mgmt/clientes/${clienteId}/lancamentos/${lancamentoId}`,
    recibosVerdesImportPreview: '/admin-mgmt/importacoes/recibos-verdes/preview',
    recibosVerdesImportConfirm: '/admin-mgmt/importacoes/recibos-verdes/confirm',
    recibosVerdesImportacoes: '/admin-mgmt/importacoes/recibos-verdes',
    faturas: '/admin-mgmt/faturas',
    faturaById: (id: string) => `/admin-mgmt/faturas/${id}`,
    faturaNotifyClient: (id: string) => `/admin-mgmt/faturas/${id}/notify-client`,
    faturaMarkPaid: (id: string) => `/admin-mgmt/faturas/${id}/mark-paid`,
    faturaMarkPending: (id: string) => `/admin-mgmt/faturas/${id}/mark-pending`,
    faturasBulkMarkPaid: '/admin-mgmt/faturas/bulk/mark-paid',
    faturasBulkMarkPending: '/admin-mgmt/faturas/bulk/mark-pending',
    faturasBulkDelete: '/admin-mgmt/faturas/bulk/delete',
    faturaAnexoUpload: (id: string) => `/admin-mgmt/faturas/${id}/anexos`,
    faturaAnexoById: (faturaId: string, anexoId: string) =>
      `/admin-mgmt/faturas/${faturaId}/anexos/${anexoId}`,
    contratos: '/admin-mgmt/contratos',
    contratoById: (id: string) => `/admin-mgmt/contratos/${id}`,
    despesasPessoal: '/admin-mgmt/despesas-pessoal',
    despesaPessoalById: (id: string) => `/admin-mgmt/despesas-pessoal/${id}`,
    segurancaSocial: '/admin-mgmt/seguranca-social',
    segurancaSocialById: (id: string) => `/admin-mgmt/seguranca-social/${id}`,
    irs: '/admin-mgmt/irs',
    irsById: (id: string) => `/admin-mgmt/irs/${id}`,
    iva: '/admin-mgmt/iva',
    ivaById: (id: string) => `/admin-mgmt/iva/${id}`,
    recibosVerdes: '/admin-mgmt/recibos-verdes',
    reciboVerdeById: (id: string) => `/admin-mgmt/recibos-verdes/${id}`,
    prestacoes: '/admin-mgmt/prestacoes',
    prestacaoById: (id: string) => `/admin-mgmt/prestacoes/${id}`,
    prestacaoPagamentos: (id: string) => `/admin-mgmt/prestacoes/${id}/pagamentos`,
    prestacaoPagamentoById: (prestacaoId: string, pagamentoId: string) =>
      `/admin-mgmt/prestacoes/${prestacaoId}/pagamentos/${pagamentoId}`,
    prestacaoPagamentoComprovativo: (prestacaoId: string, pagamentoId: string) =>
      `/admin-mgmt/prestacoes/${prestacaoId}/pagamentos/${pagamentoId}/comprovativo`,
    attachment: (entityType: string, id: string) => `/admin-mgmt/${entityType}/${id}/attachment`,
  },
  virtualization: {
    dashboard: '/virtualization/dashboard',
    settings: '/virtualization/settings',
    alerts: '/virtualization/alerts',
    alertsSummary: '/virtualization/alerts/summary',
    alertsTest: '/virtualization/alerts/test',
    alertsEvaluate: '/virtualization/alerts/evaluate',
    alertById: (id: string) => `/virtualization/alerts/${id}`,
    alertAcknowledge: (id: string) => `/virtualization/alerts/${id}/acknowledge`,
    alertSilence: (id: string) => `/virtualization/alerts/${id}/silence`,
    alertResolve: (id: string) => `/virtualization/alerts/${id}/resolve`,
    pbsServers: '/virtualization/pbs/servers',
    pbsServerById: (id: string) => `/virtualization/pbs/servers/${id}`,
    pbsServerTest: (id: string) => `/virtualization/pbs/servers/${id}/test`,
    pbsServerDetail: (id: string) => `/virtualization/pbs/servers/${id}/detail`,
    pveServers: '/virtualization/pve/servers',
    pveServerById: (id: string) => `/virtualization/pve/servers/${id}`,
    pveServerTest: (id: string) => `/virtualization/pve/servers/${id}/test`,
    pveServerDetail: (id: string) => `/virtualization/pve/servers/${id}/detail`,
    pveServerGuests: (id: string) => `/virtualization/pve/servers/${id}/guests`,
    pveServerGuestNetwork: (id: string, guestType: string, vmid: number) =>
      `/virtualization/pve/servers/${id}/guests/${guestType}/${vmid}/network`,
    pveServerGuestConsole: (id: string, guestType: string, vmid: number) =>
      `/virtualization/pve/servers/${id}/guests/${guestType}/${vmid}/console`,
    pveServerGuestSsh: (id: string, guestType: string, vmid: number) =>
      `/virtualization/pve/servers/${id}/guests/${guestType}/${vmid}/ssh`,
    pveServerGuestStart: (id: string, guestType: string, vmid: number) =>
      `/virtualization/pve/servers/${id}/guests/${guestType}/${vmid}/start`,
    pveServerGuestStop: (id: string, guestType: string, vmid: number) =>
      `/virtualization/pve/servers/${id}/guests/${guestType}/${vmid}/stop`,
    pveServerGuestIp: (id: string, guestType: string, vmid: number) =>
      `/virtualization/pve/servers/${id}/guests/${guestType}/${vmid}/ip`,
    pveServerGuestPing: (id: string, guestType: string, vmid: number) =>
      `/virtualization/pve/servers/${id}/guests/${guestType}/${vmid}/ping`,
    pveConsoleWs: (sessionId: string) => `/virtualization/pve/console-ws/${sessionId}`,
    pveSshWs: (sessionId: string) => `/virtualization/pve/ssh-ws/${sessionId}`,
    zerotierAccounts: '/virtualization/zerotier/accounts',
    zerotierAccountById: (id: string) => `/virtualization/zerotier/accounts/${id}`,
    zerotierAccountTest: (id: string) => `/virtualization/zerotier/accounts/${id}/test`,
    zerotierAccountRemoteNetworks: (id: string) =>
      `/virtualization/zerotier/accounts/${id}/networks/remote`,
    zerotierAccountNetworks: (id: string) => `/virtualization/zerotier/accounts/${id}/networks`,
    zerotierNetworks: '/virtualization/zerotier/networks',
    zerotierNetworkById: (id: string) => `/virtualization/zerotier/networks/${id}`,
    zerotierNetworkRefresh: (id: string) => `/virtualization/zerotier/networks/${id}/refresh`,
    zerotierNetworksRefreshAll: '/virtualization/zerotier/networks/refresh-all',
    zerotierNetworkMembers: (id: string) => `/virtualization/zerotier/networks/${id}/members`,
    zerotierNetworkMemberById: (networkId: string, memberId: string) =>
      `/virtualization/zerotier/networks/${networkId}/members/${memberId}`,
    zerotierJoinTargets: '/virtualization/zerotier/join-targets',
    zerotierJoinTargetById: (id: string) => `/virtualization/zerotier/join-targets/${id}`,
    zerotierJoinTargetProvision: (id: string) =>
      `/virtualization/zerotier/join-targets/${id}/provision`,
    zerotierLocalHost: '/virtualization/zerotier/local-host',
    zerotierLocalHostProvision: '/virtualization/zerotier/local-host/provision',
    zerotierLocalHostEnsureAll: '/virtualization/zerotier/local-host/ensure-all',
  },
  billing: {
    moloniStatus: '/billing/moloni/status',
    moloniCompanies: '/billing/moloni/companies',
    moloniDiagnostics: '/billing/moloni/diagnostics',
    moloniConfig: '/billing/moloni/config',
    moloniEmailConfig: '/billing/moloni/email-config',
    moloniEmailTest: '/billing/moloni/email-test',
    moloniApplyDocumentSet: '/billing/moloni/document-set/apply-recommended',
    moloniAuthUrl: '/billing/moloni/auth-url',
    moloniCallback: '/billing/moloni/callback',
    dashboard: '/billing/dashboard',
    entities: '/billing/entities',
    entityById: (id: string) => `/billing/entities/${id}`,
    entityLink: (id: string) => `/billing/entities/${id}/link`,
    entityConfirmLink: (id: string) => `/billing/entities/${id}/confirm-link`,
    entityPush: (id: string) => `/billing/entities/${id}/push`,
    entityArchive: (id: string) => `/billing/entities/${id}/archive`,
    entityRestore: (id: string) => `/billing/entities/${id}/restore`,
    archiveUnlinked: '/billing/entities/archive-unlinked',
    purgeArchived: '/billing/entities/purge-archived',
    conflicts: '/billing/conflicts',
    conflictResolve: (id: string) => `/billing/conflicts/${id}/resolve`,
    syncEntities: '/billing/sync/entities',
    syncAll: '/billing/sync/all',
    moloniResetLinks: '/billing/moloni/reset-links',
    moloniPurgeDemoData: '/billing/moloni/purge-demo-data',
    syncCatalog: '/billing/sync/catalog',
    syncDocuments: '/billing/sync/documents',
    catalog: '/billing/catalog',
    products: '/billing/products',
    productCategories: '/billing/product-categories',
    productCategoryById: (id: number | string) => `/billing/product-categories/${id}`,
    productCategoryProducts: (id: number | string) => `/billing/product-categories/${id}/products`,
    productCategoryProductsImport: (id: number | string) =>
      `/billing/product-categories/${id}/products/import`,
    moloniProducts: '/billing/moloni-products',
    moloniProductById: (id: number | string) => `/billing/moloni-products/${id}`,
    moloniProductDuplicate: (id: number | string) => `/billing/moloni-products/${id}/duplicate`,
    moloniProductFormOptions: '/billing/moloni-products/form-options',
  },
  whmcs: {
    status: '/whmcs/status',
    config: '/whmcs/config',
    testConnection: '/whmcs/test-connection',
    syncPaid: '/whmcs/sync/paid',
    invoices: '/whmcs/invoices',
    reprocess: (id: string) => `/whmcs/invoices/${id}/reprocess`,
    cronSyncPaid: '/whmcs/cron/sync-paid',
    clients: '/whmcs/clients',
    clientById: (id: number | string) => `/whmcs/clients/${id}`,
    clientEmail: (id: number | string) => `/whmcs/clients/${id}/email`,
    invoicesLive: '/whmcs/invoices/live',
    invoicesLiveBulk: '/whmcs/invoices/live/bulk',
    invoiceLiveById: (id: number | string) => `/whmcs/invoices/live/${id}`,
    invoiceSendEmail: (id: number | string) => `/whmcs/invoices/live/${id}/send-email`,
    invoiceMarkPaid: (id: number | string) => `/whmcs/invoices/live/${id}/mark-paid`,
    invoiceMarkUnpaid: (id: number | string) => `/whmcs/invoices/live/${id}/mark-unpaid`,
    invoiceCancel: (id: number | string) => `/whmcs/invoices/live/${id}/cancel`,
    paymentMethods: '/whmcs/payment-methods',
    services: '/whmcs/services',
    domains: '/whmcs/domains',
    products: '/whmcs/products',
  },
  bolt: {
    status: '/bolt/status',
    config: '/bolt/config',
    autoSync: '/bolt/auto-sync',
    testConnection: '/bolt/test-connection',
    sync: '/bolt/sync',
    dashboard: '/bolt/dashboard',
    orders: '/bolt/orders',
    orderById: (id: string) => `/bolt/orders/${id}`,
    orderPaid: (id: string) => `/bolt/orders/${id}/paid`,
    ordersBulkMarkPaid: '/bolt/orders/bulk/mark-paid',
    drivers: '/bolt/drivers',
    vehicles: '/bolt/vehicles',
    syncLogs: '/bolt/sync-logs',
    cronSyncAll: '/bolt/cron/sync/all',
  },
  viaVerde: {
    dashboard: '/via-verde/dashboard',
    movements: '/via-verde/movements',
    import: '/via-verde/import',
    movementPaid: (id: string) => `/via-verde/movements/${id}/paid`,
    movementsBulkMarkPaid: '/via-verde/movements/bulk/mark-paid',
    movementById: (id: string) => `/via-verde/movements/${id}`,
  },
  electricity: {
    dashboard: '/electricity/dashboard',
    charges: '/electricity/charges',
    import: '/electricity/import',
    chargePaid: (id: string) => `/electricity/charges/${id}/paid`,
    chargesBulkMarkPaid: '/electricity/charges/bulk/mark-paid',
    chargeById: (id: string) => `/electricity/charges/${id}`,
  },
  combustivel: {
    dashboard: '/combustivel/dashboard',
    transactions: '/combustivel/transactions',
    import: '/combustivel/import',
    transactionPaid: (id: string) => `/combustivel/transactions/${id}/paid`,
    transactionsBulkMarkPaid: '/combustivel/transactions/bulk/mark-paid',
    transactionById: (id: string) => `/combustivel/transactions/${id}`,
  },
  uber: {
    dashboard: '/uber/dashboard',
    payments: '/uber/payments',
    import: '/uber/import',
    paymentPaid: (id: string) => `/uber/payments/${id}/paid`,
    paymentsBulkMarkPaid: '/uber/payments/bulk/mark-paid',
    paymentById: (id: string) => `/uber/payments/${id}`,
  },
  pagamentos: {
    drivers: '/pagamentos/drivers',
    defaultRange: '/pagamentos/default-range',
    methods: '/pagamentos/methods',
    calculate: '/pagamentos/calculate',
    confirm: '/pagamentos/confirm',
    reports: '/pagamentos/reports',
    reportPaid: (id: string) => `/pagamentos/reports/${id}/paid`,
    reportById: (id: string) => `/pagamentos/reports/${id}`,
    reportSendEmail: (id: string) => `/pagamentos/reports/${id}/send-email`,
    reportAttachments: (id: string) => `/pagamentos/reports/${id}/attachments`,
    reportAttachmentUpload: (id: string) => `/pagamentos/reports/${id}/attachments/upload`,
    reportAttachmentDownload: (reportId: string, attachmentId: string) =>
      `/pagamentos/reports/${reportId}/attachments/${attachmentId}/download`,
    reportAttachmentById: (reportId: string, attachmentId: string) =>
      `/pagamentos/reports/${reportId}/attachments/${attachmentId}`,
  },
  contaCorrente: {
    list: '/conta-corrente',
    summary: '/conta-corrente/summary',
    drivers: '/conta-corrente/drivers',
    byId: (id: string) => `/conta-corrente/${id}`,
    attachment: (id: string) => `/conta-corrente/${id}/attachment`,
    attachmentDownload: (id: string) => `/conta-corrente/${id}/attachment/download`,
    cancel: (id: string) => `/conta-corrente/${id}/cancel`,
    reopen: (id: string) => `/conta-corrente/${id}/reopen`,
  },
  dashboardApi: {
    driverSummary: '/dashboard/driver-summary',
  },
  portalConnections: {
    list: '/portal-connections',
    byPortal: (portal: string) => `/portal-connections/${portal}`,
    autoSync: (portal: string) => `/portal-connections/${portal}/auto-sync`,
    connect: (portal: string) => `/portal-connections/${portal}/connect`,
    otp: (portal: string) => `/portal-connections/${portal}/otp`,
    /** Uber pós-OTP: submeter palavra-passe no browser vivo */
    password: (portal: string) => `/portal-connections/${portal}/password`,
    sync: (portal: string) => `/portal-connections/${portal}/sync`,
    /** Uber: listar relatórios no Supplier (Playwright) */
    reports: (portal: string) => `/portal-connections/${portal}/reports`,
    clearMessages: (portal: string) => `/portal-connections/${portal}/clear-messages`,
    /** Remove só passwordEncrypted (mantém username + sessão) */
    forgetPassword: (portal: string) => `/portal-connections/${portal}/forget-password`,
    disconnect: (portal: string) => `/portal-connections/${portal}`,
    job: (portal: string, jobId: string) => `/portal-connections/${portal}/jobs/${jobId}`,
    /** Uber Arkose: JPEG base64 do browser Playwright vivo */
    liveFrame: (portal: string, jobId: string) =>
      `/portal-connections/${portal}/jobs/${jobId}/live-frame`,
    /** Uber Arkose: clique/arrasto mapeado para page.mouse */
    liveInput: (portal: string, jobId: string) =>
      `/portal-connections/${portal}/jobs/${jobId}/live-input`,
    /** Cancela job de ligação + fecha browser vivo */
    cancelJob: (portal: string, jobId: string) =>
      `/portal-connections/${portal}/jobs/${jobId}/cancel`,
  },
  users: {
    list: '/users',
    byId: (id: string) => `/users/${id}`,
    deleteConfirmation: (id: string) => `/users/${id}/delete-confirmation`,
    status: (id: string) => `/users/${id}/status`,
    resendCredentials: (id: string) => `/users/${id}/resend-credentials`,
    resetPassword: (id: string) => `/users/${id}/reset-password`,
    meProfile: '/users/me/profile',
    meAvatar: '/users/me/avatar',
    meDocumentUpload: '/users/me/documents/upload',
    meDocumentDownload: (docId: string) => `/users/me/documents/${docId}/download`,
    meDocumentById: (docId: string) => `/users/me/documents/${docId}`,
    profile: (id: string) => `/users/${id}/profile`,
    documents: (id: string) => `/users/${id}/documents`,
    documentUpload: (id: string) => `/users/${id}/documents/upload`,
    documentDownload: (userId: string, docId: string) =>
      `/users/${userId}/documents/${docId}/download`,
    documentById: (userId: string, docId: string) => `/users/${userId}/documents/${docId}`,
    vehicles: (id: string) => `/users/${id}/vehicles`,
    vehicleById: (userId: string, vehicleId: string) => `/users/${userId}/vehicles/${vehicleId}`,
    vehiclePlatformDrivers: '/users/vehicle-platform-drivers',
  },
  auditLogs: { list: '/audit-logs' },
  search: { global: '/search' },
  smtp: {
    config: '/smtp-config',
    emailRouting: '/smtp-config/email-routing',
    test: '/smtp-config/test',
  },
  tenantBranding: {
    info: '/tenant/branding',
    logo: (version?: string) =>
      version
        ? `/tenant/branding/logo?v=${encodeURIComponent(version)}`
        : '/tenant/branding/logo',
    wallpaper: (version?: string) =>
      version
        ? `/tenant/branding/wallpaper?v=${encodeURIComponent(version)}`
        : '/tenant/branding/wallpaper',
  },
  publicTenantBranding: {
    info: (siteId: string) => `/public/tenant-branding?siteId=${encodeURIComponent(siteId)}`,
    logo: (siteId: string, version?: string) => {
      const base = `/public/tenant-branding/logo?siteId=${encodeURIComponent(siteId)}`;
      return version ? `${base}&v=${encodeURIComponent(version)}` : base;
    },
    wallpaper: (siteId: string, version?: string) => {
      const base = `/public/tenant-branding/wallpaper?siteId=${encodeURIComponent(siteId)}`;
      return version ? `${base}&v=${encodeURIComponent(version)}` : base;
    },
  },
  platform: {
    features: '/platform/features',
    hostStats: '/platform/host-stats',
    smsConfig: '/platform/sms-config',
    smsFeatures: '/platform/sms-config/features',
    smsTest: '/platform/sms-config/test',
    smsHistory: '/platform/sms-config/history',
    whatsappSettings: '/platform/whatsapp/settings',
    whatsappStatus: '/platform/whatsapp/status',
    whatsappQr: '/platform/whatsapp/qr',
    whatsappLogout: '/platform/whatsapp/logout',
    whatsappRestart: '/platform/whatsapp/restart',
    whatsappTemplates: '/platform/whatsapp/templates',
    whatsappTemplateByKey: (key: string) => `/platform/whatsapp/templates/${key}`,
    whatsappTest: '/platform/whatsapp/test',
    whatsappTenantsOverview: '/platform/whatsapp/tenants',
    fail2ban: {
      list: '/platform/fail2ban',
      unblock: '/platform/fail2ban/unblock',
    },
  },
  whatsappBusiness: {
    config: '/whatsapp-business/config',
    status: '/whatsapp-business/status',
    sendMessage: '/whatsapp-business/messages/send',
    templates: '/whatsapp-business/templates',
    templatesManage: '/whatsapp-business/templates/manage',
    sendTemplate: '/whatsapp-business/templates/send',
    templateHeaderUrl: '/whatsapp-business/templates/header-url',
    notificationEvents: '/whatsapp-business/notification-events',
    notificationEventByKey: (eventKey: string) =>
      `/whatsapp-business/notification-events/${encodeURIComponent(eventKey)}`,
    provider: '/whatsapp-business/provider',
  },
  emailTemplates: {
    list: '/email-templates',
    byKey: (key: string) => `/email-templates/${key}`,
  },
} as const;

/** localStorage keys for auth tokens. */
export const STORAGE_KEYS = {
  accessToken: 'cms_token',
  refreshToken: 'cms_refresh',
  activeWorkspaceId: 'cms_workspace_id',
  rememberedSiteId: 'cms_remembered_site_id',
} as const;
